apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: nke6d523e-go 
  janus-idp.io/tekton: nke6d523e-go
  backstage.io/kubernetes-id: nke6d523e-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nke6d523e-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml